#!/usr/bin/env sh
echo "This device needs two systemd services: llama-server, then the chatbot."
echo ""
echo "1) /etc/systemd/system/llama-server.service"
echo "   Loads the GGUF model once and keeps it resident in RAM."
echo "   ---"
echo "   [Unit]"
echo "   Description=llama.cpp inference server"
echo "   After=multi-user.target"
echo ""
echo "   [Service]"
echo "   Type=simple"
echo "   User=pi"
echo "   EnvironmentFile=/home/pi/Multi Language Chatbot/raspberry/.env"
echo "   ExecStart=/home/pi/Multi Language Chatbot/raspberry/scripts/start_llama_server.sh"
echo "   Restart=on-failure"
echo "   RestartSec=5"
echo ""
echo "   [Install]"
echo "   WantedBy=multi-user.target"
echo "   ---"
echo ""
echo "2) /etc/systemd/system/chatbot.service"
echo "   Runs the chatbot app; depends on llama-server already being active."
echo "   ---"
echo "   [Unit]"
echo "   Description=Offline Multilingual OLED Chatbot"
echo "   After=llama-server.service"
echo "   Requires=llama-server.service"
echo ""
echo "   [Service]"
echo "   Type=simple"
echo "   User=pi"
echo "   WorkingDirectory=/home/pi/Multi Language Chatbot"
echo "   EnvironmentFile=/home/pi/Multi Language Chatbot/raspberry/.env"
echo "   ExecStart=/usr/bin/python3 -m raspberry.app.main"
echo "   Restart=on-failure"
echo "   RestartSec=5"
echo ""
echo "   [Install]"
echo "   WantedBy=multi-user.target"
echo "   ---"
echo ""
echo "Then:"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl enable llama-server.service chatbot.service"
echo "   sudo systemctl start llama-server.service"
echo "   sudo systemctl start chatbot.service"
